name: Post Merge Check

on:
  pull_request_target: 
    types: [closed]

jobs:
  post-merge-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check for lock
        id: lock_check
        run: |
          # Placeholder for script to check terraform lock
          # For now it is a 50/50 chance
          if [ $((RANDOM % 2)) -eq 0 ]; then
            echo "final_check=true" >> $GITHUB_OUTPUT
          else
            echo "final_check=false" >> $GITHUB_OUTPUT
          fi
      - name: Final check
        if: steps.lock_check.outputs.final_check == 'true'
        run: |
          # Placeholder for script to check terraform lock
          # For now it is a 50/50 chance
          if [ $((RANDOM % 2)) -eq 0 ]; then
            echo "final_check=true" >> $GITHUB_OUTPUT
          else
            echo "final_check=false" >> $GITHUB_OUTPUT
          fi
      - name: Post merge check
        run: |
          if [ $(grep -c "final_check=true" $GITHUB_OUTPUT) -eq 2 ]; then
            echo "Post merge check passed"
          else
            echo "Post merge check failed"
            exit 1
          fi
