name: Terraform Plan

on:
  workflow_dispatch:
    inputs:
      working_dir:
        default: "./terraform/env"

      # NOTE: Please keep these in sync with ../../.terra*-version files.
      tf_version: { default: "1.6.4" }
      tg_version: { default: "0.53.5" }

  pull_request:
    types: [opened, synchronize, reopened]

env:
  working_dir: "ENV:./terraform/env"
  tf_version: "ENV:1.6.4"
  tg_version: "ENV:0.53.5"

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: show context
        run: |
          jq . <<< '{
            "github": ${{ toJSON(github) }}
            "env": ${{ toJSON(env) }}
            "vars": ${{ toJSON(vars) }}
            "job": ${{ toJSON(job) }}
            "jobs": ${{ toJSON(jobs) }}
            "steps": ${{ toJSON(steps) }}
            "runner": ${{ toJSON(runner) }}
            "secrets": ${{ toJSON(secrets) }}
            "strategy": ${{ toJSON(strategy) }}
            "matrix": ${{ toJSON(matrix) }}
            "needs": ${{ toJSON(needs) }}
            "inputs": ${{ toJSON(inputs) }}
          }'
